version: '3.8'

services:
  app:
    build: .
    container_name: dbdocs-app
    ports:
      - "8081:8081"
    env_file:
      - .env-prod
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: dbdocs-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dbdocs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:  