spring:
  application:
    name: dbdocs
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_OAUTH2_CLIENT_ID}
            client-secret: ${GITHUB_OAUTH2_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  datasource:
    url: ${DBDOCS_DB_URL}
    username: ${DBDOCS_DB_USERNAME}
    password: ${DBDOCS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    
  # JPA configuration  
  jpa:
    properties:
      hibernate:
        default_schema: dbdocs
    hibernate:
      ddl-auto: update
  
  # Vô hiệu hóa Javers hoàn toàn
  javers:
    enabled: false

jwt:
  expiration: 86400000  # 24 hours in milliseconds
  secret: c2VjcmV0LWtleS1mb3ItZGJkb2NzLWFwcC1kZXZlbG9wbWVudC0yMDI1LTA2LTExLXZpc3NvZnQ=  # Base64 encoded secret key

server:
  port: 8080

google:
  oauth2:
    client_id: ${GOOGLE_OAUTH2_CLIENT_ID}
    client_secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}

# SpringDoc OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: false
  packages-to-scan: com.vissoft.vn.dbdocs.interfaces.rest
