spring:
  application:
    name: dbdocs
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_OAUTH2_CLIENT_ID}
            client-secret: ${GITHUB_OAUTH2_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  datasource:
    url: ${DBDOCS_DB_URL}
    username: ${DBDOCS_DB_USERNAME}
    password: ${DBDOCS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    
  # JPA configuration  
  jpa:
    properties:
      hibernate:
        default_schema: dbdocs
    hibernate:
      ddl-auto: update
  
  # Vô hiệu hóa Javers hoàn toàn
  javers:
    enabled: false

  # Cấu hình CORS
  web:
    cors:
      # Chỉ định cụ thể các domain được phép, KHÔNG dùng "*" với allowCredentials=true
      allowed-origins: ${CORS_ALLOWED_ORIGINS}
      # Cho phép sử dụng mẫu
      allowed-origin-patterns: "*" 
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
      allowed-headers: "*"
      exposed-headers: "Authorization, Content-Disposition"
      allow-credentials: true
      max-age: 3600
      
  # Cho phép ghi đè bean definition
  main:
    allow-bean-definition-overriding: true

jwt:
  expiration: 86400000  # 24 hours in milliseconds
  secret: c2VjcmV0LWtleS1mb3ItZGJkb2NzLWFwcC1kZXZlbG9wbWVudC0yMDI1LTA2LTExLXZpc3NvZnQ=  # Base64 encoded secret key

server:
  port: 8080

# CORS Configuration
cors:
  # Thêm cấu hình chi tiết cho CORS
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://dbdocs.mmoall.com}
  allowed-origin-patterns: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
  allowed-headers: "*"
  exposed-headers: "Authorization, Content-Disposition"
  allow-credentials: true
  max-age: 3600

google:
  oauth2:
    client_id: ${GOOGLE_OAUTH2_CLIENT_ID}
    client_secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}

# SpringDoc OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: false
  packages-to-scan: com.vissoft.vn.dbdocs.interfaces.rest
domain:
  frontend:
    url: ${VITE_FRONTEND_URL}
